apiVersion: apps/v1
kind: Deployment
metadata:
    name: slave-deployment
    labels: 
      app: db_slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db_slave
  template:
    metadata:
      labels:
        app: db_slave
    spec:
      # make sure master and slave pods are created on different nodes
      # if a node already has a pod with defined label, then next pod wont be scheduled on same node
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              # pod label key
              - key: app
                operator: In
                values:
                # pod label value (can be eather db_master or db_slave, but needs to be same in master-yaml and slave-yaml)
                - db_master
            topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: queries-volume
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: queries
            # An array of keys from the ConfigMap to create as files
            items:
            - key: "query1.sql"
              # path is here only file name which is stored under /db-queries
              path: "query1.sql"
      containers:
        - name: postgres-slave
          image: yurinek/postgres_slave:12_k8s
          ports:
            - containerPort: 5439
          resources:
            requests:
              memory: "300Mi"
              cpu: "0.5"
            limits:
              memory: "400Mi"
              cpu: "1"
          volumeMounts:
            - name: queries-volume
              mountPath: "/db-queries"
              readOnly: true
          env:
          - name: RUNTIME_ENV_MASTER_HOST
            value: "master-cluster-dns-name"
          - name: RUNTIME_ENV_PG_VERSION_PULL
            value: "12"
          - name: RUNTIME_ENV_PG_CLUSTER_PATH
            value: "/data_alternate"
          - name: RUNTIME_ENV_PG_PORT
            value: "5439"
          - name: RUNTIME_ENV_PG_DB
            value: "obscure_db"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-auth
                key: password
